# Generated by Django 6.0.2 on 2026-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('off', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(max_length=25)),
                ('count', models.IntegerField(default=1)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField()),
                ('is_delete', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
    ]
