# Generated by Django 6.0.2 on 2026-05-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_alter_product_options_alter_product_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
