# Generated by Django 6.0.2 on 2026-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_category_remove_product_test_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('hex_code', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
                'db_table': 'Color_table',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='products_app.color'),
        ),
    ]
