# Generated by Django 6.0.2 on 2026-05-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_alter_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
