# Generated by Django 6.0.2 on 2026-05-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_alter_color_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت تخفیف'),
        ),
    ]
