# Generated by Django 6.0.2 on 2026-05-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_product_off_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='products_app.color'),
        ),
    ]
