# Generated by Django 6.0.2 on 2026-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
