# Generated by Django 6.0.2 on 2026-06-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0016_product_album'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product_album',
            table='product_album',
        ),
    ]
