# Generated by Django 6.0.2 on 2026-06-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0017_alter_product_album_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_album',
        ),
    ]
