# Generated by Django 6.0.2 on 2026-06-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0019_product_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_album',
        ),
    ]
