# Generated by Django 6.0.2 on 2026-06-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0022_attribute_productattributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=100, verbose_name='مقدار'),
        ),
    ]
