# Generated by Django 6.0.2 on 2026-06-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0023_alter_productattributevalue_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'ویژگی ', 'verbose_name_plural': 'ویژگی ها '},
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='Attribute_table',
        ),
        migrations.AlterModelTable(
            name='productattributevalue',
            table='ProductAttributeValue_table',
        ),
    ]
