# Generated by Django 6.0.2 on 2026-06-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0024_alter_productattributevalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/assets/img/no-image.png/', upload_to='products/%Y/%m/%d/'),
        ),
    ]
