# Generated by Django 6.0.2 on 2026-06-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0025_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_you_need_to_complete_this',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
