# Generated by Django 6.0.2 on 2026-06-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0026_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_you_need_to_complete_this',
            new_name='image',
        ),
    ]
