# Generated by Django 6.0.2 on 2026-06-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0027_rename_image_you_need_to_complete_this_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='important_attribute',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
