# Generated by Django 6.0.2 on 2026-06-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0028_productattributevalue_important_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='important_attribute',
            field=models.BooleanField(blank=True, default='خیر', null=True, verbose_name='ویژگی مهم'),
        ),
    ]
