# Generated by Django 6.0.2 on 2026-06-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0029_alter_productattributevalue_important_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='topic_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_attribute', to='products_app.topic_attribute'),
        ),
    ]
