# Generated by Django 6.0.2 on 2026-06-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0030_topic_attribute_attribute_topic_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic_attribute',
            options={'verbose_name': 'ویژگی های اصلی ', 'verbose_name_plural': 'ویژگی اصلی'},
        ),
        migrations.AlterModelTable(
            name='topic_attribute',
            table='Topic_attribute_table',
        ),
    ]
