# Generated by Django 6.0.2 on 2026-06-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0031_alter_topic_attribute_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='topic_attribute',
        ),
        migrations.DeleteModel(
            name='Topic_attribute',
        ),
    ]
