# Generated by Django 6.0.2 on 2026-06-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0032_remove_attribute_topic_attribute_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='Attribute_1',
        ),
    ]
